version: '2'
services:
  postgresdb:
    build: docker/pg/
    volumes:
      - db-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=departments
    expose:
      - 5432
    ports:
      - 5432:5432
  departments:
    build: docker/web_app/
    environment:
      - MYAPP_JDBC_URL=jdbc:postgresql://postgresdb:5432/departments
      - MYAPP_JDBC_USER=postgres
      - MYAPP_JDBC_PASS=postgres
    expose:
      - 8080
    ports:
      - 8080:8080
    depends_on:
      - postgresdb
    links:
      - postgresdb
volumes:
  db-data:
